feat: Query and update animals table
rashedarman/vet-clinic-database pull request #2
Opened 2023-02-28 14:27 UTC by rashedarman

Hi there :wave:

As per requirement, I am sharing the screenshots of the results obtained from running SQL queries.

![s1](https://user-images.githubusercontent.com/78993606/221881097-8160bd9a-68cf-41c8-8b92-d81bffae3fbb.png)

---

![s2](https://user-images.githubusercontent.com/78993606/221881113-ff65e435-af5b-4581-86e7-e82c1ecd7d5a.png)

---

![s3](https://user-images.githubusercontent.com/78993606/221881119-3a7f62af-33a8-4127-814c-a0fff982eade.png)

---

![s4](https://user-images.githubusercontent.com/78993606/221881126-715485f5-2cc4-4141-aa17-2968d8935116.png)

---

![s5](https://user-images.githubusercontent.com/78993606/221881136-3eaf0f03-24d1-41d2-ab67-80dbb99dee65.png)

2023-02-28 14:33 UTC, youmari requested changes
Hi @rashedarman , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
✔️ Great commit messages
✔️ PRO PR
✔️ No linter error 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-28 14:33 UTC, youmari commented on schema.sql
> +    species VARCHAR(100),
- [ ] it would be better to remove this line cause it will be added by alter command in thee data.sql  if you keep it return an error ` ERROR:  column "species" of relation "animals" already exists`

2023-02-28 14:51 UTC, Lucas-Masaba approved these changes
# Hello @rashedarman  👋 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![almost-there](https://media.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif)

## Highlights 🍾 
- Thank you for making changes as requested by the previous reviewer 👍 

## Optional suggestions 💭 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏 💻 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Lucas-Masaba in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-28 14:53 UTC, merged

2023-05-01 16:01 UTC, christianbiring1 reviewed
Hi @rashedarman , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
# STATUS: APPROVED :tada: 

## Highlights

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._